### ISSUE TITLE
Architectural Review

### ISSUE THREAD

**Issue by fabwu** [wuethrich44/zusammenfassung-enapp#15]

**Comment by fabwu** [comment]
@alexsuter Wollen wir das überhaupt dokumentieren? Ich habe keine Notizen und Folien gibts auch keine?

**Comment by alexsuter** [comment]
@wuethrich44 
simon ( @red0point ) hat sich notzen gemacht - siehe studentbox. vielleicht kann ers in einem abschnitt zusammenfassen - sonst lassen wirs. ich habe auch keine.

**Comment by fabwu** [comment]
@alexsuter Schön dass du unser PAWI-Projekt benutzt :wink:

**Comment by simonerni** [comment]
Hab mal alle meine Notizen strukturiert und dokumentiert. Spannende Sache.
