### ISSUE TITLE
EJB Tier

### ISSUE THREAD

**Issue by fabwu** [wuethrich44/zusammenfassung-enapp#4]

**Comment by alexsuter** [comment]
Die Kontrollfragen habe ich von der Notenstatistik - müssen wir dann nochmal anschauen, sobald diese auf Illias sind.

**Comment by simonerni** [comment]
2.11 - Vom lokalen Client aus gesehen ist die Lokalität des Beans auf
das er zugreift, nicht transparent.

Was meint das genau? Wie nicht transparent?

**Comment by fabwu** [comment]
@red0point Joho hat den Text von [diesem Tutorial](http://docs.oracle.com/javaee/6/tutorial/doc/gipjf.html) geklaut (Abschnitt Local Clients). Da steht einfach beim lokalen Zugriff ist der Ort nicht transparent (ist ja auf der gleichen VM) und beim remote Zugriff ist er transparent (Client weiss ja nicht genau wo die Bean steckt). Ich denke ist aber nicht so wichtig.
